name: "Astro Diagnostics"

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
jobs:
  diagnostics:
    name: Run Astro Diagnostics
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Install nub.js
        uses: nubjs/setup-nub@v0

      - name: Install dependencies
        run: nub install
      - name: Run Astro Diagnostics
        run: nub run astro check
